# fly.toml app configuration file generated for backend-divine-snow-4097 on 2025-05-07T15:22:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-divine-snow-4097'
primary_region = 'bog'

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = 'shared-cpu-1x'
